cmake_minimum_required(VERSION 3.5)

PROJECT(TEST_SOCKET)
if (DEFINED LINUX)
message("Начинаю сборку под Linux")
set(CPP_FILES ${CMAKE_BINARY_DIR}/src/main.cpp ${CMAKE_BINARY_DIR}/src/client.cpp)
set(CMAKE_BUILD_TYPE Release)
add_executable(${PROJECT_NAME} ${CPP_FILES})
set_target_properties(${PROJECT_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/build RUNTIME_OUTPUT_NAME "Client")
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_BINARY_DIR}/hdr)
endif()
